### ISSUE TITLE
How to ignore created_by on models from packages?

### ISSUE THREAD

**Issue by casenjo** [GeneaLabs/laravel-governor#22]
Hi Mike! 

I recently added an [auditing package](https://github.com/owen-it/laravel-auditing) into my application and I'm unable to use it out of the box because Governor tries to add the user ID into the created_by column of the package's table, but of course it's not present.

It's a slightly annoying to have to extend the model(s) of a package just to add the `protected $isGoverned = false;` statement (or having to create migrations for the package's tables to add the created_by column instead). Is there a way to avoid this?

I was thinking maybe having a special config file could be used as a blacklist for model classes that Governor should ignore but I'm not sure if that's the best solution.

**Comment by mikebronner** [comment]
@casenjo So sorry for the long delay !!! I have been unable to work on this package due to work demands, but am looking at it again now. You have a very valid point. I will think on this and see what we can do, perhaps all models are by default false, and we only govern models that are explicitly brought into the fold.
